### ISSUE TITLE
mediaDevices API isn't working on Facebook in-app browser

### ISSUE THREAD

**Issue by jenmoisessanchez** [philnash/mediadevices-camera-selection#3]
The app works perfectly fine on chrome but when it is accessed from in-app Facebook browser mediaDevices api is not working.

**Comment by philnash** [comment]
I've not tested this myself in the in-app Facebook browser, but it doesn't surprise me. Here's a Stack Overflow answer with a good set of reasons why it might not be working for you: https://stackoverflow.com/a/52991288/28376.

In this case, I'd recommend handling the failure then try to determine if the reason the API failed is because you're inside Facebook and displaying a message to encourage the user to open the site in the device native browser (Chrome or Safari).

**Comment by jenmoisessanchez** [comment]
Thanks @philnash that's a very helpful article. Apparently it is the access to getUserMedia being blocked by the in-app browser. Will do the displaying a message to use native browser.
